# Generated by Django 6.0.7 on 2026-07-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_session_code', models.CharField(max_length=50, unique=True)),
                ('organisation', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
                ('facilitator', models.CharField(max_length=255)),
                ('session_date', models.DateField()),
                ('attendees', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('raw_rows_count', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized_session_code'], name='ingestion_c_normali_d7774e_idx'), models.Index(fields=['organisation'], name='ingestion_c_organis_c8b01c_idx'), models.Index(fields=['programme'], name='ingestion_c_program_e96df4_idx'), models.Index(fields=['session_date'], name='ingestion_c_session_23989f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawSessionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
                ('facilitator', models.CharField(max_length=255)),
                ('session_date', models.DateField()),
                ('attendees', models.PositiveIntegerField()),
                ('source_file', models.CharField(max_length=255)),
                ('normalized_session_code', models.CharField(max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('source_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized_session_code'], name='ingestion_r_normali_feea4d_idx'), models.Index(fields=['organisation'], name='ingestion_r_organis_6a20f8_idx'), models.Index(fields=['programme'], name='ingestion_r_program_f04702_idx'), models.Index(fields=['session_date'], name='ingestion_r_session_97e859_idx'), models.Index(fields=['source_file'], name='ingestion_r_source__dfdd10_idx')],
            },
        ),
    ]
